project:
  type: website

website:
  title: "Lennard Berger's blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/Fohlen

format:
  html:
    include-in-header:
      text: |
        <script data-goatcounter="https://fohlen.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    theme:
      light: flatly
      dark: darkly
    css: styles.css
