project:
  type: website

website:
  title: "Lennard Berger's blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/Fohlen
  google-analytics:
    tracking-id: "G-L4ESZR26GV"
    anonymize-ip: true
    storage: none

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
