project:
  type: website

website:
  title: "Lennard Berger personal web page"
  navbar:
    right:
      - icon: github
        href: https://github.com/Fohlen
format:
  html:
    theme: cosmo
    css: styles.css
