project:
  type: website

website:
  title: "Lennard Berger's blog"
  navbar:
    right:
      - icon: github
        href: https://github.com/Fohlen
  comments:
    giscus:
      repo: Fohlen/fohlen.github.io
      category: announcements

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
