[package]
name = "embedding_network"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.116"
serde = { version = "1.0.198", features = ["derive"] }
tqdm = "0.7.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
